language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
install:
- wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
- bii setup:cpp
- bii --version
script:
- cmake --version
- bii init biicode_project
- mkdir -p ./biicode_project/blocks/google/gtest
- mv !(biicode_project) ./biicode_project/blocks/google/gtest
- cd biicode_project
- bii find -um
- bii cpp:build
- ./bin/google_gtest_src_gtest_main
- ./bin/google_gtest_samples_sample10_unittest
- ls ./bin/google_gtest_fused-src_gtest_gtest_main
- ls ./bin/google_gtest_test_gtest_color_test_
- ls ./bin/google_gtest_test_gtest_no_test_unittest
- ls ./bin/google_gtest_test_gtest_throw_on_failure_ex_test
- ls ./bin/google_gtest_test_gtest_environment_test
- ls ./bin/google_gtest_test_gtest_output_test_
- ls ./bin/google_gtest_test_gtest_throw_on_failure_test_
- ls ./bin/google_gtest_samples_sample9_unittest
- ls ./bin/google_gtest_test_gtest_env_var_test_
- ls ./bin/google_gtest_test_gtest_premature_exit_test
- ls ./bin/google_gtest_test_gtest_uninitialized_test_
- ls ./bin/google_gtest_test_gtest_filter_unittest_
- ls ./bin/google_gtest_test_gtest_repeat_test
- ls ./bin/google_gtest_test_gtest-unittest-api_test
- ls ./bin/google_gtest_test_gtest_break_on_failure_unittest_
- ls ./bin/google_gtest_test_gtest-listener_test
- ls ./bin/google_gtest_test_gtest_shuffle_test_
- ls ./bin/google_gtest_test_gtest_xml_output_unittest_
- ls ./bin/google_gtest_test_gtest_catch_exceptions_test_
- ls ./bin/google_gtest_test_gtest_list_tests_unittest_
- ls ./bin/google_gtest_test_gtest_stress_test
after_success:
- bii user google -p $BII_GOOGLE_PASSWORD
# - bii publish
env:
  global:
    secure: PKktr+B56gmTZtlmLn2g4lJj8PXRhokL+RqQti/MulFFVlSqqDvRnv1VSBggqm58MVpvY1ScWcsFthA1S8NC+bGmYukSy270JAyftgS6ur69uSyhc2DSBH/yLQ1IFxBi/6YXgv7v63PmN0u2cObHk2otFwHJtuslcE8Wh6uR4rQ=
